version: '3.4'

services:

  postgres_shop:
    image: postgres:13.8
    container_name: postgres_shop
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: shop_db
    ports:
      - "5444:5432"
    networks:
      - shop

networks:
  shop:
    driver: bridge
