version: '3.9'

services:

  postgres_db:
    image: postgres
    container_name: postgres_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: shop_db
    ports:
      - "5444:5432"
