spring:
  datasource:
    url: jdbc:postgresql://localhost:5444/shop_db
    username: admin
    password: admin
  jpa:
    show-sql: true
  flyway:
    enabled: true
    locations:
      classpath:/db/postgres/migration, 
      classpath:/db/postgres/patch
  data:
    rest:
      base-path: /api/v1
      default-page-size: 50

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    org:
      springframework:
        security: DEBUG

server:
  port: 8081